import nodemailer from "nodemailer";
import { getConfig } from "../utils/config.js";

let transporter;

/**
 * Initialize or return a nodemailer transporter from env config.
 */
function getTransporter() {
  const {
    EMAIL_HOST, EMAIL_PORT, EMAIL_USER, EMAIL_PASS
  } = getConfig();

  if (!EMAIL_HOST || !EMAIL_USER || !EMAIL_PASS) return null;

  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: EMAIL_HOST,
      port: Number(EMAIL_PORT) || 587,
      secure: Number(EMAIL_PORT) === 465, // true for 465, false for 587
      auth: {
        user: EMAIL_USER,
        pass: EMAIL_PASS
      }
    });
  }
  return transporter;
}

/**
 * Send email to configured recipients.
 * If email config or recipients are missing, resolves without sending.
 */
export async function sendEmail({ subject, html, text }) {
  const { EMAIL_FROM, EMAIL_RECIPIENTS } = getConfig();
  if (!EMAIL_FROM || !EMAIL_RECIPIENTS.length) {
    return { sent: false, message: "Email not configured or no recipients" };
  }
  const tx = getTransporter();
  if (!tx) {
    return { sent: false, message: "SMTP transporter not configured" };
  }
  try {
    const info = await tx.sendMail({
      from: EMAIL_FROM,
      to: EMAIL_RECIPIENTS,
      subject,
      text: text || "",
      html: html || ""
    });
    return { sent: true, messageId: info.messageId };
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("Email send error:", err.message);
    return { sent: false, error: err.message };
  }
}

/**
 * Build a simple HTML email with a short table of metadata.
 */
export function buildEmailTemplate({ title, intro, meta = [] }) {
  const rows = meta
    .map(m => `<tr><td style="padding:4px 8px;"><b>${m.title}</b></td><td style="padding:4px 8px;">${m.value}</td></tr>`)
    .join("");
  return `
  <div style="font-family: Arial, Helvetica, sans-serif; line-height: 1.4;">
    <h2>${title}</h2>
    <p>${intro}</p>
    ${rows ? `<table style="border-collapse: collapse; border: 1px solid #eee;">${rows}</table>` : ""}
    <p style="color:#666; font-size: 12px;">This message was generated by the Alert Service.</p>
  </div>
  `;
}
